# fly.toml app configuration file generated for sehr-viel-sehr on 2025-01-04T14:45:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sehr-viel-sehr'
primary_region = 'arn'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
destination = "/pb/pb_data"
source = "pb_data"
